python_binary(
    name = 'cooee',
    main_module = 'cooee',
    platform = 'py3',
    deps = [
        ':lib',
        '//third_party:click',
        '//third_party:requests',
        '//third_party:urllib3',
        '//third_party:chardet',
        '//third_party:certifi',
        '//third_party:idna',
    ],
)

python_library(
    name = 'lib',
    srcs = glob(['*.py']),
    visibility = [
        'PUBLIC',
    ],
)